Repository keymanapp/status.keyman.com, pull requests merged in 2019-10, with the labels that each got.

#6 Use hovercard to reduce the pull request review status based on GitHub's algorithm, rather than trying to figure it out ourselves.
  code.js
  public/src/app/pull-request/pull-request.component.ts
Labels: bug

#7 Update tier build status for stable and support pending status
  code.js
  public/src/app/app.component.ts
Labels: bug, enhancement

#8 Dim the 'beta' column if we are not currently in beta
  code.js
  public/src/app/app.component.css
  public/src/app/app.component.html
  public/src/app/app.component.ts
Labels: enhancement

#9 Support multiple milestones
  public/src/app/app.component.html
  public/src/app/app.component.ts
Labels: bug, enhancement

#10 Show contributions
  README.md
  code.js
  current-sprint.js
  github-contributions.js
  github-status.js
  public/src/app/app.component.css
  public/src/app/app.component.html
  public/src/app/app.component.ts
  public/src/app/app.module.ts
  public/src/app/pipes/filter-object-by-date.pipe.ts
Labels: enhancement

#11 The Great Big Avatar Fix
  public/src/app/app.component.css
  public/src/app/app.component.html
  public/src/app/app.component.ts
Labels: bug

#12 The Great Big Avatar Fix Again
  public/src/app/app.component.css
  public/src/app/app.component.html
  public/src/app/pull-request/pull-request.component.css
  public/src/app/pull-request/pull-request.component.html
  public/src/styles.css
Labels: bug

#13 fix: Milestone Other really should be 'no:milestone' on site links
  public/src/app/app.component.html
Labels: bug

#14 change: update stock favicon.ico to be Keyman icon
  public/src/favicon.ico
Labels: enhancement
