Repository keymanapp/status.keyman.com, pull requests merged in 2021-07, with the labels that each got.

#127 fix: version number extraction on pso and llso
  server/services/deployment/linux-lsdev-sil-org.ts
  server/services/deployment/packages-sil-org.ts
Labels: fix

#131 feat: fade in
  public/src/app/app.component.css
  public/src/app/deploy-box/deploy-box.component.css
  public/src/app/issue-list/issue-list.component.css
  public/src/app/pull-request/pull-request.component.css
  public/src/app/sentry/sentry.component.css
Labels: feat

#132 feat: show change counts in PRs
  public/package-lock.json
  public/package.json
  public/src/app/issue-list/issue-list.component.html
  public/src/app/pull-request/pull-request.component.css
  public/src/app/pull-request/pull-request.component.html
  public/src/app/pull-request/pull-request.component.ts
  public/tsconfig.json
Labels: feat

#133 feat: split crash reports by tier
  public/src/app/app.component.css
  public/src/app/app.component.html
  public/src/app/app.component.ts
  public/src/app/sentry/sentry.component.css
  public/src/app/sentry/sentry.component.html
  public/src/app/sentry/sentry.component.ts
  server/code.ts
  server/services/github/github-status.ts
  server/services/sentry/sentry-issues.ts
Labels: feat

#134 fix: teamcity polling
  server/code.ts
Labels: fix

#135 chore: teamcity diag
  server/util/DataChangeTimingManager.ts
Labels: chore

#136 feat: emoji grouped pulls
  public/src/app/app.component.css
  public/src/app/app.component.html
  public/src/app/app.component.ts
  public/src/app/platforms.ts
  public/src/app/pull-request/pull-request.component.css
  public/src/app/pull-request/pull-request.component.html
  public/src/app/pull-request/pull-request.component.ts
Labels: feat

#139 fix: handle site failures with catch
  public/angular.json
  server/code.ts
  server/util/httpget.ts
Labels: fix

#140 chore: additional error handlers
  public/src/main.ts
  server/code.ts
  server/util/httpget.ts
  server/util/httppost.ts
Labels: fix

#141 feat: show test runs for stable tier
  public/src/app/app.component.html
  public/src/app/app.component.ts
Labels: feat
