Repository keymanapp/status.keyman.com, pull requests merged in 2021-09, with the labels that each got.

#151 fix: Allow to build server
  README.md
  server/package.json
Labels: fix

#152 fix: pull request status
  public/src/app/home/home.component.ts
  public/src/app/pull-request/pull-request.component.css
  public/src/app/pull-request/pull-request.component.html
  public/src/app/pull-request/pull-request.component.ts
Labels: feat, fix

#154 fix: linked issues
  README.md
  public/src/app/issue-list/issue-list.component.css
  public/src/app/issue-list/issue-list.component.html
  public/src/app/pull-request/pull-request.component.css
  public/src/app/pull-request/pull-request.component.html
  server/keymanapp-test-bot/keymanapp-test-bot-middleware.ts
  server/services/github/github-issues.ts
  server/services/github/github-status.ts
Labels: fix

#155 fix: retest support for suites and groups
  server/test/manual-test-parser.spec.ts
  shared/manual-test/manual-test-parser.ts
  shared/manual-test/manual-test-protocols.ts
Labels: fix

#156 fix: don't process closed issues
  server/keymanapp-test-bot/keymanapp-test-bot.ts
Labels: fix

#160 chore: add link to test spec to test results
  shared/manual-test/manual-test-parser.ts
Labels: chore

#158 fix: persist popups
  public/src/app/app.module.ts
  public/src/app/deploy-box/deploy-box.component.ts
  public/src/app/home/home.component.html
  public/src/app/issue-list/issue-list.component.ts
  public/src/app/popup-coordinator.service.ts
  public/src/app/popup/popup.component.css
  public/src/app/popup/popup.component.ts
  public/src/app/pull-request/pull-request.component.ts
  public/src/app/sentry/sentry.component.ts
Labels: fix

#159 fix: duplicate timeline items
  public/src/app/home/home.component.ts
  public/src/app/issue-list/issue-list.component.html
  public/src/app/issue-list/issue-list.component.ts
Labels: fix

#161 chore: fixup tests
  server/test/manual-test-parser.spec.ts
Labels: chore
