Repository keymanapp/status.keyman.com, pull requests merged in 2021-03, with the labels that each got.

#67 fix: put clipboard lists in date order
  public/src/app/app.component.ts
Labels: fix

#69 fix: correct milestone sorting
  public/src/app/app.component.ts
Labels: fix

#71 feat: highlight issues that have associated PRs
  public/src/app/issue-list/issue-list.component.html
  public/src/app/issue-list/issue-list.component.ts
Labels: feat

#77 feat: websocket-based notifications
  package-lock.json
  package.json
  public/angular.json
  public/package-lock.json
  public/package.json
  public/src/app/app.component.html
  public/src/app/app.component.ts
  public/src/app/datasocket/datasocket.service.ts
  public/src/app/status/status.service.ts
  public/src/environments/environment.prod.ts
  public/src/environments/environment.ts
  public/src/typings.d.ts
  server/_start_server.sh
  server/code.js
  server/code.ts
  server/current-sprint.ts
  server/data.ts
  server/data/status-data.ts
  server/identity/github.ts
  server/package-lock.json
  server/package.json
  server/services/downloads.keyman.com/version.js
  server/services/downloads.keyman.com/version.ts
  server/services/github/github-contributions.ts
  server/services/github/github-issues.ts
  server/services/github/github-status.ts
  server/services/sentry/sentry.ts
  server/services/teamcity/teamcity.ts
  server/util/httpget.ts
  server/util/httppost.ts
Labels: feat

#79 chore: production
  public/src/environments/environment.ts
Labels: chore

#80 fix: stable build reporting
  public/src/app/app.component.ts
  public/src/app/platforms.ts
Labels: fix

#82 feat: add sentry
  public/package-lock.json
  public/package.json
  public/src/main.ts
  server/code.ts
  server/package-lock.json
  server/package.json
Labels: feat

#83 chore: production builds
  public/package.json
  public/src/environments/environment.ts
Labels: fix

#84 chore: fixup build error
  public/src/app/app.component.html
Labels: fix

#86 feat: more webhooks
  server/code.ts
  server/data/status-data.ts
  server/package-lock.json
  server/package.json
  server/util/DataChangeTimingManager.ts
Labels: feat

#87 chore: timing for teamcity as well
  server/code.ts
Labels: chore

#89 feat: show active sentry issue details
  public/src/app/app.component.css
  public/src/app/app.component.html
  public/src/app/app.component.ts
  public/src/app/platforms.ts
  public/src/app/sentry/sentry.component.css
  public/src/app/sentry/sentry.component.html
  public/src/app/sentry/sentry.component.ts
  public/src/app/sites.ts
  public/src/app/status/status.service.ts
  server/code.ts
  server/data/status-data.ts
  server/package-lock.json
  server/package.json
  server/services/downloads.keyman.com/version.ts
  server/services/sentry/sentry-issues.ts
  server/services/sentry/sentry.ts
  server/services/teamcity/teamcity.ts
  server/util/httpget.ts
Labels: feat

#90 feat: cleanup issue list, add scroll etc
  public/src/app/app.component.css
  public/src/app/app.component.html
  public/src/app/issue-list/issue-list.component.css
  public/src/app/issue-list/issue-list.component.html
  public/src/app/issue-list/issue-list.component.ts
  public/src/app/sentry/sentry.component.css
Labels: feat

#91 chore: staging to master
  .github/workflows/staging_com-keyman-staging-status.yml
  README.md
  _start_server.sh
  code.js
  github-contributions.js
  github-issues.js
  github-status.js
  package-lock.json
  package.json
  public/angular.json
  public/package-lock.json
  public/package.json
  public/src/app/app.component.css
  public/src/app/app.component.html
  public/src/app/app.component.ts
  public/src/app/datasocket/datasocket.service.ts
  public/src/app/issue-list/issue-list.component.css
  public/src/app/issue-list/issue-list.component.html
  public/src/app/issue-list/issue-list.component.ts
  public/src/app/platforms.ts
  public/src/app/sentry/sentry.component.css
  public/src/app/sentry/sentry.component.html
  public/src/app/sentry/sentry.component.ts
  public/src/app/sites.ts
  public/src/app/status/status.service.ts
  public/src/environments/environment.prod.ts
  public/src/environments/environment.ts
  public/src/main.ts
  public/src/typings.d.ts
  server/.eslintrc.js
  server/.gitignore
  server/_start_server.bat
  server/_start_server.sh
  server/code.ts
  server/current-sprint.ts
  server/data.ts
  server/data/status-data.ts
  server/identity/github.ts
  server/package-lock.json
  server/package.json
  server/services/downloads.keyman.com/version.ts
  server/services/github/github-contributions.ts
  server/services/github/github-issues.ts
  server/services/github/github-status.ts
  server/services/sentry/sentry-issues.ts
  server/services/teamcity/teamcity.ts
  server/tsconfig.json
  server/util/DataChangeTimingManager.ts
  server/util/httpget.ts
  server/util/httppost.ts
Labels: chore

#92 feat: other repos box
  .github/workflows/master_status-keyman-com.yml
  .github/workflows/staging_com-keyman-staging-status.yml
  public/src/app/app.component.css
  public/src/app/app.component.html
  public/src/app/app.component.ts
  public/src/app/count-box/count-box.component.html
  public/src/app/issue-list/issue-list.component.html
  public/src/app/sites.ts
Labels: feat

#93 fix: clean othersite pulls before refresh
  public/src/app/app.component.ts
Labels: fix

#95 feat: flex box fixes scroll bar
  public/src/app/app.component.css
  public/src/app/app.component.html
Labels: feat

#97 fix: horz gravity for issue list popups
  public/src/app/app.component.html
  public/src/app/issue-list/issue-list.component.css
  public/src/app/issue-list/issue-list.component.html
  public/src/app/issue-list/issue-list.component.ts
  public/src/app/pull-request/pull-request.component.html
  public/src/app/pull-request/pull-request.component.ts
  public/src/app/sentry/sentry.component.html
  public/src/app/sentry/sentry.component.ts
  public/src/styles.css
Labels: fix

#98 fix: gravity for popups
  public/src/app/app.component.html
  public/src/app/issue-list/issue-list.component.css
  public/src/app/issue-list/issue-list.component.html
  public/src/app/issue-list/issue-list.component.ts
  public/src/app/pull-request/pull-request.component.css
  public/src/app/pull-request/pull-request.component.html
  public/src/app/pull-request/pull-request.component.ts
  public/src/app/sentry/sentry.component.css
  public/src/app/sentry/sentry.component.html
  public/src/app/sentry/sentry.component.ts
  public/src/styles.css
  server/code.ts
Labels: fix

#99 fix: order contributions by date
  public/src/app/pipes/filter-object-by-date.pipe.ts
Labels: fix

#101 fix: sentry width to 800px
  public/src/app/sentry/sentry.component.css
Labels: fix

#102 chore: popup position
  public/src/app/issue-list/issue-list.component.css
Labels: chore

#103 chore: gravity-right
  public/src/app/app.component.html
Labels: chore
