Repository keymanapp/status.keyman.com, pull requests merged in 2021-06, with the labels that each got.

#123 feat: Add Linux deployment status for beta and alpha versions
  public/src/app/app.component.ts
  public/src/app/deploy-box/deploy-box.component.ts
  server/code.ts
  server/data/status-data.ts
  server/services/deployment/linux-lsdev-sil-org-alpha.ts
  server/services/deployment/linux-lsdev-sil-org-beta.ts
  server/services/deployment/linux-lsdev-sil-org-stable.ts
  shared/status-source.ts
Labels: enhancement

#124 fix: cleanup linux targets
  public/src/app/app.component.css
  public/src/app/app.component.ts
  public/src/app/deploy-box/deploy-box.component.ts
  server/code.ts
  server/data/status-data.ts
  server/services/deployment/launch-pad.ts
  server/services/deployment/linux-lsdev-sil-org-alpha.ts
  server/services/deployment/linux-lsdev-sil-org-beta.ts
  server/services/deployment/linux-lsdev-sil-org-stable.ts
  server/services/deployment/linux-lsdev-sil-org.ts
  server/util/httpget.ts
  shared/status-source.ts
Labels: fix

#125 fix: Launchpad url
  public/src/app/deploy-box/deploy-box.component.ts
Labels: bug
