Repository keymanapp/status.keyman.com, pull requests merged in 2022-04, with the labels that each got.

#235 feat: highlight PRs that close issues
  public/src/app/issue-list/issue-list.component.css
  public/src/app/issue-list/issue-list.component.html
  public/src/app/issue-list/issue-list.component.ts
  server/services/github/github-issues.ts
Labels: feat

#236 feat: count box shows unfixed count
  public/src/app/count-box/count-box.component.css
  public/src/app/count-box/count-box.component.html
  public/src/app/count-box/count-box.component.ts
  public/src/app/issue-list/issue-list.component.html
  public/src/app/issue-list/issue-list.component.ts
Labels: feat

#237 feat: report on test contributions
  public/src/app/home/home.component.html
  public/src/app/home/home.component.ts
  server/data/status-data.ts
  server/services/github/github-test-contributions.ts
Labels: feat

#238 chore: Update Debian package name
  public/src/app/deploy-box/deploy-box.component.ts
  server/services/deployment/debian.ts
Labels: chore

#239 fix: show keyboard and model PRs and issues again
  public/src/app/home/home.component.html
Labels: fix

#240 feat: popups for keyboards + lexical models
  public/src/app/app.module.ts
  public/src/app/home/home.component.html
  public/src/app/home/home.component.ts
  public/src/app/issue-list/issue-list.component.html
  public/src/app/pull-request-list/pull-request-list.component.css
  public/src/app/pull-request-list/pull-request-list.component.html
  public/src/app/pull-request-list/pull-request-list.component.spec.ts
  public/src/app/pull-request-list/pull-request-list.component.ts
  public/src/app/pull-request/pull-request.component.css
  public/src/app/pull-request/pull-request.component.html
Labels: feat

#241 chore: ensure title doesn't appear in header row
  public/src/app/pull-request/pull-request.component.html
Labels: chore

#242 chore: negation
  public/src/app/pull-request/pull-request.component.html
Labels: chore

#244 feat: testflight artifact link
  server/keymanapp-test-bot/artifact-links-comment.ts
  server/keymanapp-test-bot/test-artifact-links.ts
  server/package-lock.json
  server/services/teamcity/teamcity.ts
  shared/artifact-links.ts
Labels: feat

#249 feat: tweak artifact links
  server/code.ts
  server/keymanapp-test-bot/artifact-links-comment.ts
  server/keymanapp-test-bot/test-artifact-links.ts
  shared/artifact-links.ts
Labels: feat
