Repository keymanapp/status.keyman.com, pull requests merged in 2024-02, with the labels that each got.

#421 chore: logging
  server/code.ts
  server/services/github/github-status.ts
Labels: chore

#422 fix: Adjust for changed Linux artifact names
  server/keymanapp-test-bot/artifact-links-comment.ts
Labels: fix

#425 fix: use live s.keyman.com host
  server/services/deployment/s-keyman-com.ts
Labels: fix

#426 chore: manage rate limits for GitHub
  server/code.ts
  server/data/status-data.ts
  server/services/github/github-contributions.ts
  server/services/github/github-issues.ts
  server/services/github/github-status.ts
  server/services/github/github-test-contributions.ts
  server/util/github-rate-limit.ts
Labels: fix

#427 chore: skip archived repos
  server/code.ts
  server/services/github/github-status.ts
Labels: chore

#428 chore: beta less purple
  public/src/app/pull-request/pull-request.component.css
Labels: chore

#429 chore: no box shadow on beta
  public/src/app/pull-request/pull-request.component.css
Labels: chore

#431 feat: refactor to tabbed user views
  public/src/app/app.module.ts
  public/src/app/assigned-issues/assigned-issues.component.css
  public/src/app/assigned-issues/assigned-issues.component.html
  public/src/app/assigned-issues/assigned-issues.component.ts
  public/src/app/contributions-tab/contributions-tab.component.css
  public/src/app/contributions-tab/contributions-tab.component.html
  public/src/app/contributions-tab/contributions-tab.component.ts
  public/src/app/contributions/contribution-collection.ts
  public/src/app/contributions/contributions.component.css
  public/src/app/contributions/contributions.component.html
  public/src/app/contributions/contributions.component.ts
  public/src/app/home/home.component.css
  public/src/app/home/home.component.html
  public/src/app/home/home.component.ts
  public/src/app/issue-list/issue-list.component.ts
  public/src/state.ts
Labels: feat

#432 refactor: data into data.model.ts and overview tab into new component
  public/src/app/app.module.ts
  public/src/app/assigned-issues/assigned-issues.component.ts
  public/src/app/contributions-home/contributions-home.component.html
  public/src/app/contributions-tab/contributions-tab.component.html
  public/src/app/contributions-tab/contributions-tab.component.ts
  public/src/app/contributions/contributions.component.ts
  public/src/app/data/contributions.model.ts
  public/src/app/data/data.model.ts
  public/src/app/home/home.component.html
  public/src/app/home/home.component.ts
  public/src/app/overview-tab/overview-tab.component.css
  public/src/app/overview-tab/overview-tab.component.html
  public/src/app/overview-tab/overview-tab.component.ts
  public/src/state.ts
  server/services/deployment/s-keyman-com.ts
Labels: refactor
